version: 0.2.0.{build}
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup target add i686-pc-windows-msvc
  - rustc --version
  - cargo --version
  - rustup --version
  - rustup target list
cache:
  - '%USERPROFILE%\.rustup'
  - '%USERPROFILE%\.cargo'
  - target
build_script:
  - cargo build --verbose --release --features=build --target x86_64-pc-windows-msvc
  - cargo build --verbose --release --features=build --target i686-pc-windows-msvc
after_build:
  - 7z a target/ut181a-cli_32bit.zip target/i686-pc-windows-msvc/release/ut181a-cli.exe
  - 7z a target/ut181a-cli_64bit.zip target/x86_64-pc-windows-msvc/release/ut181a-cli.exe
test: off
artifacts:
  - path: target/ut181a-cli_32bit.zip
    name: MSVC32
  - path: target/ut181a-cli_64bit.zip
    name: MSVC64
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: uu2RXA1CcjTjKs8qz94eVtPJigzLyCeoogUu5Dzu42E/421V8TUpm4dzhI9pkik3
    artifact: MSVC32, MSVC64
    draft: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true