version: 0.2.0.{build}
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain stable --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup target add i686-pc-windows-msvc
  - rustc --version
  - cargo --version
  - rustup --version
  - rustup target list
cache:
  - '%USERPROFILE%\.rustup'
  - '%USERPROFILE%\.cargo'
  - target
build_script:
  - cargo build --verbose --release --features=build --target x86_64-pc-windows-msvc
  - cargo build --verbose --release --features=build --target i686-pc-windows-msvc
after_build:
  - 7z a target/ut181a-cli_32bit.zip target/i686-pc-windows-msvc/release/ut181a-cli.exe
  - 7z a target/ut181a-cli_64bit.zip target/x86_64-pc-windows-msvc/release/ut181a-cli.exe
test: off
deploy: off
artifacts:
  - path: target/ut181a-cli_32bit.zip
    name: MSVC32
  - path: target/ut181a-cli_64bit.zip
    name: MSVC64